import random
import numpy as np
from collections import Counter
from typing import List, Dict, Tuple
from openai import OpenAI
import torch


class LLM:
    def __init__(self, api_key, base_url, model_name='deepseek-reasoner'):
        self.client = OpenAI(api_key=api_key, base_url=base_url)
        self.model_name = model_name

    def generate(self, messages):
        """
        messages: Dialogue history list, where each element contains 'role' and 'content'.
        reasoning_content: The thought process generated by an LLM while answering questions.
        answer: The LLM's answer for the question.
        """
        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=messages
        )
        reasoning_content = response.choices[0].message.reasoning_content
        answer = response.choices[0].message.content

        return reasoning_content, answer


class MedPromptLLM:
    def __init__(self, llm, questions: List[str], answers : List[str], options : List[str], BasePromptPath='./BasePrompt.txt', MedPromptPath='./MedPrompt.txt', so_flag=False, vote_count: int = 5, kn_flag=False, k: int = 5, embedding_model=None, embedding_tokenizer=None, med_knowledge=None):
        """
        Input:
            llm: Large language model.
            questions: List of medical questions (training set).
            answers: List of answers for medical questions (training set).
            options: Answer options for the question.
            corvariate: A dict containing all patients' basic information: gender, age, height, weight.
            MedPromptPath: Path of the txt file containing the template of MedPrompt.
            MedPromptPath: Path of the txt file containing the template of BasePrompt.
            so_flag: Shuffle options flag, when so_flag=Ture, the answer options for the question will be shuffled for
                     vote_count times. If the question is a binary classification task, so_flag need to be False.
            vote_count: Number of shuffling.
            kn_flag: kNN flag, when kn_flag=Ture, the k nearest questions in embedding space will be included in the MedPrompt when answering a question.
            k: para for kNN.
            embedding_model: pre-trained model used for question embedding.
            embedding_tokenizer: pre-trained tokenizer for the embedding model.
            med_knowledge: Medical knowledge used to construct MedPrompt.
        Class:
            self.dataset: List of question - answer dict.
            self.dataset_reasoning:  List of question - reasoning - answer dict.
            self.dataset_vectors: List of embedding vectors of questions.
        """
        self.llm = llm
        with open(BasePromptPath, "r", encoding="utf-8") as file:
            self.BasePrompt = file.read()
        with open(MedPromptPath, "r", encoding="utf-8") as file:
            self.MedPrompt_temp = file.read()
        if med_knowledge:
            self.MedPrompt_temp.replace('...', med_knowledge)
        self.questions = questions
        self.answers = answers
        self.dataset = []
        self.k = k
        self.so_flag = so_flag
        if self.so_flag:
            self.vote_count = vote_count
        else:
            self.vote_count = None
        self.options = options

        self.kn_flag = kn_flag
        if self.kn_flag:
            self.embedding_model = embedding_model
            self.embedding_tokenizer = embedding_tokenizer
        else:
            self.embedding_model = None
            self.embedding_tokenizer = None
        self.format_dataset()
        self.dataset_reasoning = self.filter_dataset()
        if self.kn_flag:
            self.dataset_vectors = np.array([self.embed(sample['question']) for sample in self.dataset_reasoning]).squeeze()
        else:
            self.dataset_vectors = None

    def attach_options(self, question):
        """
        Attach options to a question.
        """
        return f"{question}\n" + "\n".join([f"{chr(65 + i)}: {opt}" for i, opt in enumerate(self.options)])

    def format_dataset(self):
        """
        Standardize the Q&A training set into dictionary format.
        """
        for i, q in enumerate(self.questions):
            sample_dict = {'question': self.attach_options(q), 'answer': self.answers[i]}
            self.dataset.append(sample_dict)

    def embed(self, text: str) -> np.ndarray:
        """embed question to vector"""
        input = self.embedding_tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=100)
        with torch.no_grad():
            output = self.embedding_model(**input).last_hidden_state.mean(dim=1)
        return output.detach().cpu().numpy()

    def filter_dataset(self) -> List[Dict]:
        """Delete the questions that LLM cannot answer correctly and
        LLM is harnessed to generate CoT(reasoning) for the remaining sample in dataset"""
        filtered_data = []
        for sample in self.dataset:
            question, true_answer = sample['question'], sample['answer']
            messages = [{'role': 'system', 'content': self.BasePrompt},
                        {'role': 'user', 'content': question}]
            reasoning_content, answer = self.llm.generate(messages)
            if true_answer in answer:
                print('LLM correctly answers the question, the sample is added to prompt set.')
                filtered_data.append({
                    'question': question,
                    'reasoning': reasoning_content,
                    'answer': true_answer
                })
            else:
                print('LLM cannot correctly answers the question, the sample is discarded.')

        return filtered_data

    def kn_search(self, target_question: str) -> List[Dict]:
        """k nearest neighbor algorithm for prompt example selection"""
        target_vector = self.embed(target_question)
        distances = np.linalg.norm(self.dataset_vectors - target_vector, axis=1)
        nearest_indices = distances.argsort()[:self.k]
        return [self.dataset_reasoning[i] for i in nearest_indices]

    def shuffle_options(self, question: str) -> Tuple[str, Dict[str, str]]:
        """shuffle the options in target question"""
        shuffled_options = self.options.copy()
        random.shuffle(shuffled_options)
        option_mapping = {chr(65 + i): self.options.index(opt) for i, opt in enumerate(shuffled_options)}
        formatted_question = f"{question}\n" + "\n".join(
            [f"{chr(65 + i)}: {opt}" for i, opt in enumerate(shuffled_options)])
        return formatted_question, option_mapping

    def generate_answer(self, problem: str) -> str:
        if self.kn_flag:
            similar_samples = self.kn_search(problem)
        else:
            similar_samples = random.sample(self.dataset_reasoning, self.k)

        promt_examples = ''
        for similar_sample in similar_samples:
            promt_examples += '问题:\n'
            promt_examples += similar_sample['question']
            promt_examples += '\n'
            promt_examples += '推理:\n'
            promt_examples += similar_sample['reasoning']
            promt_examples += '\n'
            promt_examples += '答案:\n'
            promt_examples += similar_sample['answer']
            promt_examples += '\n'
            promt_examples += '\n'
        MedPrompt = self.MedPrompt_temp.replace('*', promt_examples)
        print('MedPrompt:\n', MedPrompt)
        print(f'LLM with MedPrompt is thinking...')
        if self.so_flag:
            vote_results = []
            answer_reasoning_contents = []
            for _ in range(self.vote_count):
                options_shuffled_question, mapping = self.shuffle_options(problem)
                messages = [{'role': 'system', 'content': MedPrompt},
                            {'role': 'user', 'content': options_shuffled_question}]
                reasoning_content, answer = self.llm.generate(messages)
                for j, option in enumerate(self.options):
                    if option in answer:
                        vote_results.append(j)
                        answer_reasoning_contents.append((j, answer, reasoning_content))
                        break
            most_common_index = Counter(vote_results).most_common(1)[0][0]
            final_answer = random.choice(
                [answer for idx, answer, reasoning in answer_reasoning_contents if idx == most_common_index])
            reasoning_content = random.choice(
                [reasoning for idx, answer, reasoning in answer_reasoning_contents if idx == most_common_index])
        else:
            messages = [{'role': 'system', 'content': MedPrompt},
                        {'role': 'user', 'content': self.attach_options(problem)}]
            reasoning_content, final_answer = self.llm.generate(messages)
        print(f'LLM with MedPrompt answer complete.')
        return reasoning_content, final_answer
